# Generated by Django 5.1.3 on 2024-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reader_address',
            field=models.TextField(default='Default address'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reference_id',
            field=models.CharField(max_length=100),
        ),
    ]
