# Generated by Django 5.1.3 on 2024-11-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_reader_reader_address_alter_reader_reader_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
