# Generated by Django 5.1.3 on 2024-11-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0006_news_image_alter_reader_reader_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
